package presentacion;

public enum Eventos {
	SUB_PANELES,
	SUB_PERSONAL,
	SUB_EQUIPAJE,
	SUB_OPERACIONES,
	SUB_FINANCIERA,
	SUB_INCIDENCIAS,
	SUB_LOCALES,
	SUB_ESTACIONAMIENTO,
	SUB_VUELOS,
	SUB_SEGURIDAD
}

